"""Initial migration

Revision ID: ab45a4a7b45e
Revises: 
Create Date: 2026-08-07 14:12:39.507824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab45a4a7b45e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_Category')
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('imageUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('createdAt',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updatedAt',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('Category_name_key'))
        batch_op.create_index(batch_op.f('ix_Category_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Category_name'), ['name'], unique=True)

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deliveryLocation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('deliveryNotes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('paymentMethod', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('paymentStatus', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transactionId', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('paidAt', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('isUrgent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('urgentFee', sa.Float(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('totalAmount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'ORDERED'"))
        batch_op.alter_column('createdAt',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updatedAt',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_Order_id'), ['id'], unique=False)
        batch_op.drop_constraint(batch_op.f('Order_userId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Order_userId_User'), 'User', ['userId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('OrderItem', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('orderId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('productId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_OrderItem_id'), ['id'], unique=False)
        batch_op.drop_constraint(batch_op.f('OrderItem_orderId_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('OrderItem_productId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_OrderItem_productId_Product'), 'Product', ['productId'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_OrderItem_orderId_Order'), 'Order', ['orderId'], ['id'])

    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('imageUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('categoryId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('createdAt',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updatedAt',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_Product_id'), ['id'], unique=False)
        batch_op.drop_constraint(batch_op.f('Product_categoryId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Product_categoryId_Category'), 'Category', ['categoryId'], ['id'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collegeName', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('passwordHash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'USER'"))
        batch_op.alter_column('accommodationType',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('addressDetails',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('createdAt',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updatedAt',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('User_email_key'))
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_id'))
        batch_op.drop_index(batch_op.f('ix_User_email'))
        batch_op.create_index(batch_op.f('User_email_key'), ['email'], unique=1)
        batch_op.alter_column('updatedAt',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('createdAt',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('addressDetails',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('accommodationType',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'USER'"))
        batch_op.alter_column('passwordHash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('avatar')
        batch_op.drop_column('year')
        batch_op.drop_column('phone')
        batch_op.drop_column('course')
        batch_op.drop_column('collegeName')

    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Product_categoryId_Category'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Product_categoryId_fkey'), 'Category', ['categoryId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_Product_id'))
        batch_op.alter_column('updatedAt',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('createdAt',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('categoryId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('imageUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('stock')

    with op.batch_alter_table('OrderItem', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_OrderItem_orderId_Order'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_OrderItem_productId_Product'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('OrderItem_productId_fkey'), 'Product', ['productId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('OrderItem_orderId_fkey'), 'Order', ['orderId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_OrderItem_id'))
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('productId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('orderId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Order_userId_User'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Order_userId_fkey'), 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_Order_id'))
        batch_op.alter_column('updatedAt',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('createdAt',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'ORDERED'"))
        batch_op.alter_column('totalAmount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('urgentFee')
        batch_op.drop_column('isUrgent')
        batch_op.drop_column('paidAt')
        batch_op.drop_column('transactionId')
        batch_op.drop_column('paymentStatus')
        batch_op.drop_column('paymentMethod')
        batch_op.drop_column('deliveryNotes')
        batch_op.drop_column('deliveryLocation')

    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Category_name'))
        batch_op.drop_index(batch_op.f('ix_Category_id'))
        batch_op.create_index(batch_op.f('Category_name_key'), ['name'], unique=1)
        batch_op.alter_column('updatedAt',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('createdAt',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('imageUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_Category',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('imageUrl', sa.VARCHAR(), nullable=True),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updatedAt', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
